# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Schroeder's Programming Blog
email: deadlydog@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my tips, tricks, and code to help other developers be more productive.
baseurl:
url: https://deadlydog.github.io
twitter_username: deadlydog
github_username: deadlydog

remote_theme: mmistakes/minimal-mistakes@26c1989 # Specify the branch, tag, or commit so that if they breaks the theme with updates, it won't affect our site. Remove the '@' and everything after it to use the tip of the master branch.
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"
search: true # Show the search link on the site.

# Build settings
markdown: kramdown
github: [metadata] # Added this to avoid the "No GitHub API authentication could be found. Some fields may be missing or have incorrect data." warning when starting Jekyll.

# Uncomment to show line numbers in code blocks by default.
# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true

# Outputting
permalink: /:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Additional non-standard directories to process and create HTML files from markdown pages.
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Schroeder"
  avatar : "/assets/Site/bio-photo.jpg"
  bio    : "aka deadlydog. Developer and family man. Loves C#, .NET, PowerShell, AutoHotkey. Automate Everything!"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/deadlydog"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deadlydog"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/1danielschroeder/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/deadlydog"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deadlydog"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/1danielschroeder/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      toc_label: Post Sections
      toc_icon: stream
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: false
      toc_label: Post Sections
      toc_icon: stream
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
